add car service into dev
nonavai/CarSharingApp pull request #2
Opened 2024-02-14 09:35 UTC by nonavai

2024-02-19 15:16 UTC, katyalys requested changes

2024-02-19 15:16 UTC, katyalys commented on CarSharingApp.CarService/CarSharingApp.CarService.Infrastructure/DataBase/Configurations/CarConfiguration.cs
> +
better use HasMaxLength as it will throw exception if text length more than 30 characters and HasColumnType will just truncate your text

2024-02-19 15:16 UTC, katyalys commented on CarSharingApp.CarService/CarSharingApp.CarService.Infrastructure/Repositories/CarStateRepository.cs
> +        var entity = await _dataBase.CarStates.FirstAsync(a => a.CarId == id, cancellationToken: token);
make more explicit naming of a

2024-02-19 15:16 UTC, katyalys commented on CarSharingApp.CarService/CarSharingApp.CarService.Infrastructure/Repositories/CommentRepository.cs
> +        return _dataBase.Comments.Where(f => f.CarId == id).AsEnumerable();
same

2024-02-19 15:16 UTC, katyalys commented on CarSharingApp.CarService/CarSharingApp.CarService.WebAPI/Controllers/CarController.cs
> +    [Route("")]
why do you use just empty quotes in route naming? delete them

2024-02-19 15:16 UTC, katyalys commented on CarSharingApp.CarService/CarSharingApp.CarService.WebAPI/Controllers/ImageController.cs
> +    //[Authorize(Roles = RoleNames.Lender)]
delete comments

2024-02-19 15:16 UTC, katyalys commented on CarSharingApp.CarService/CarSharingApp.CarService.WebAPI/Consumers/DeleteCarConsumer.cs
> +        await _mediator.Send(context.Message);
from which microservice do you get this message?

2024-02-19 15:23 UTC, nonavai commented on CarSharingApp.CarService/CarSharingApp.CarService.Application/CommandHandlers/CarCommandHandlers/DeleteCarByUserHandler.cs
> +            throw new NotFoundException("Cars");
in class NotFoundException it automatically writes other info
here:
`public NotFoundException(string message) : base(message + " Not Found") { }`

2024-02-19 15:23 UTC, nonavai commented on CarSharingApp.CarService/CarSharingApp.CarService.Application/CommandHandlers/CarCommandHandlers/DeleteCarHandler.cs
> +            throw new NotFoundException("Car");
in class NotFoundException it automatically writes other info
here:
`public NotFoundException(string message) : base(message + " Not Found") { }`

2024-02-19 15:24 UTC, nonavai commented on CarSharingApp.CarService/CarSharingApp.CarService.Application/CommandHandlers/CommentCommandHandlers/DeleteCommentHandler.cs
> +            throw new NotFoundException("Comment");
in class NotFoundException it automatically writes other info
here:
`public NotFoundException(string message) : base(message + " Not Found") { }`

2024-02-19 15:30 UTC, nonavai commented on CarSharingApp.CarService/CarSharingApp.CarService.WebAPI/Consumers/DeleteCarConsumer.cs
> +        await _mediator.Send(context.Message);
identity service will publish it, i gonna implement the logic in identity soon

2024-02-22 21:19 UTC, katyalys approved these changes

2024-02-26 12:41 UTC, merged